# SPDX-License-Identifier: GPL-2.0
# process_package.toml

image_dir = "../../build/app"

default_flags = ["user", "exec"]
default_stack_size = 4096

[[images]]
name = "app1"
file = "app1.elf"
args = ["--verbose"]
env = [
    "PATH=/bin",
    "TERM=vt100",
]

[images.auxv]
AT_PAGESZ = 4096
AT_CLKTCK = 100


[[images]]
name = "app2"
file = "app2.elf"
args = ["arg1", "arg2"]

[[images]]
name = "app3"
file = "app3.elf"
args = ["arg1", "arg2"]

[[images]]
name = "app4"
file = "app4.elf"
args = ["arg1", "arg2"]

[[images]]
name = "app5"
file = "app5.elf"
args = ["arg1", "arg2"]

[[images]]
name = "app6"
file = "app6.elf"
args = ["arg1", "arg2"]

[[images]]
name = "app7"
file = "app7.elf"
args = ["arg1", "arg2"]

[[images]]
name = "app8"
file = "app8.elf"
args = ["arg1", "arg2"]

[[images]]
name = "app9"
file = "app9.elf"
args = ["arg1", "arg2"]

[[images]]
name = "app10"
file = "app10.elf"
args = ["arg1", "arg2"]

# [[images]]
# name = "raw_test"
# type = "flat"
# file = "raw_test.bin"
# load_hint = 0x40000000
# entry_hint = 0x40000000