# SPDX-License-Identifier: GPL-2.0
# obj-y += mmio.o
obj-y += fixmap.o
obj-y += ioremap.o
obj-y += early_ioremap.o
obj-y += memblock.o
obj-y += mm.o
obj-y += pm.o
obj-y += vm.o
obj-y += map_kernel.o
obj-y += kmalloc.o
obj-y += mapping.o
obj-y += uaccess.o
